services:
  prospero:
    env_file: .env
    image: ghcr.io/nicba1010/prospero:latest
    volumes:
      - prospero_data:/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - prospero_net

volumes:
  prospero_data:
    name: prospero_data

networks:
  prospero_net:
    name: prospero_network
    driver: bridge
